"""edit tickers

Revision ID: 99ef5d866002
Revises: 4b5040cc3a3c
Create Date: 2024-03-15 23:12:58.363802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "99ef5d866002"
down_revision: Union[str, None] = "4b5040cc3a3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickers",
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_unique_constraint(None, "tickers", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "tickers", type_="unique")
    op.drop_column("tickers", "symbol")
    # ### end Alembic commands ###
