"""delete prev price

Revision ID: a8d934cf29e6
Revises: e517219b3086
Create Date: 2024-03-20 16:18:08.702673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8d934cf29e6'
down_revision: Union[str, None] = 'e517219b3086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ticker_price', ['id'])
    op.drop_column('ticker_price', 'prev_close_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_price', sa.Column('prev_close_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticker_price', type_='unique')
    # ### end Alembic commands ###
